/* Runs ON real GNU/Hurd amd64 (see mkhurd.sh). Prints Go source for
 * syscall/ztypes_hurd_amd64.go from the real glibc headers: field order,
 * offsets and sizes are taken from offsetof/sizeof, gaps become explicit
 * Pad_cgo_N fields, and compile-time size assertions are appended so a wrong
 * layout can never build silently. Integer field widths and signedness are
 * derived from the C types, never guessed. */
#define _GNU_SOURCE
#include <sys/types.h>
#include <dirent.h>
#include <fcntl.h>
#include <signal.h>
#include <termios.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stddef.h>
#include <unistd.h>
#include <limits.h>
#include <sys/resource.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <net/if.h>
#include <netinet/in.h>
#include <netinet/icmp6.h>
#include <netinet/tcp.h>

struct fld {
	size_t off, size;
	const char *name;
	const char *type; /* NULL: derive an integer type from size/sign */
	int sign;         /* 'i' or 'u' when type == NULL */
	size_t elems;     /* != 0: array of elems elements */
};

static struct fld fl[64];
static int nf;
static const char *cur;
static size_t cursize;
static const char *asserted[64];
static size_t assertedsz[64];
static int nasserted;

static void begin(const char *goname, size_t size)
{
	nf = 0;
	cur = goname;
	cursize = size;
}

static void addf(size_t off, size_t size, const char *name, const char *type, int sign, size_t elems)
{
	fl[nf].off = off;
	fl[nf].size = size;
	fl[nf].name = name;
	fl[nf].type = type;
	fl[nf].sign = sign;
	fl[nf].elems = elems;
	nf++;
}

/* Integer scalar; signedness detected from the C type. */
#define FS(S, f, go) addf(offsetof(S, f), sizeof(((S *)0)->f), go, NULL, \
		((__typeof__(((S *)0)->f))-1 < 0) ? 'i' : 'u', 0)
/* Scalar with an explicit Go type (struct, pointer). */
#define FT(S, f, go, ty) addf(offsetof(S, f), sizeof(((S *)0)->f), go, ty, 0, 0)
/* Array of esz-byte elements of Go type ty. */
#define FA(S, f, go, ty, esz) addf(offsetof(S, f), sizeof(((S *)0)->f), go, ty, 0, \
		sizeof(((S *)0)->f) / (esz))

static int cmp(const void *a, const void *b)
{
	const struct fld *x = a, *y = b;
	return x->off < y->off ? -1 : x->off > y->off;
}

static void end(int check)
{
	int i, pad = 0;
	size_t pos = 0;
	char tb[32];

	qsort(fl, nf, sizeof fl[0], cmp);
	printf("type %s struct {\n", cur);
	for (i = 0; i < nf; i++) {
		const char *t;
		if (fl[i].off > pos)
			printf("\tPad_cgo_%d [%d]byte\n", pad++, (int)(fl[i].off - pos));
		if (fl[i].type)
			t = fl[i].type;
		else {
			snprintf(tb, sizeof tb, "%sint%d", fl[i].sign == 'u' ? "u" : "", (int)fl[i].size * 8);
			t = tb;
		}
		if (fl[i].elems)
			printf("\t%s [%d]%s\n", fl[i].name, (int)fl[i].elems, t);
		else
			printf("\t%s %s\n", fl[i].name, t);
		pos = fl[i].off + fl[i].size;
	}
	if (check && cursize > pos)
		printf("\tPad_cgo_%d [%d]byte\n", pad++, (int)(cursize - pos));
	printf("}\n\n");
	if (check) {
		asserted[nasserted] = cur;
		assertedsz[nasserted] = cursize;
		nasserted++;
	}
}

static size_t sockaddr_any_size;

#define INTTYPE(name, T) printf("type %s %sint%d\n\n", name, \
		((T)-1 < 0) ? "" : "u", (int)sizeof(T) * 8)
#define SZ(name, T) printf("\t%s = 0x%zx\n", name, sizeof(T))

int main(void)
{
	printf("// Code generated by poc/mkztypes_hurd.c run on real GNU/Hurd amd64; DO NOT EDIT.\n\n");
	printf("package syscall\n\nimport \"unsafe\"\n\n");
	printf("const (\n");
	printf("\tsizeofPtr = 0x%zx\n", sizeof(void *));
	printf("\tsizeofShort = 0x%zx\n", sizeof(short));
	printf("\tsizeofInt = 0x%zx\n", sizeof(int));
	printf("\tsizeofLong = 0x%zx\n", sizeof(long));
	printf("\tsizeofLongLong = 0x%zx\n", sizeof(long long));
#ifdef PATH_MAX
	printf("\tPathMax = 0x%x\n", PATH_MAX);
#else
	printf("\tPathMax = 0x1000 // Hurd has no PATH_MAX\n");
#endif
	printf(")\n\n");
	printf("type (\n\t_C_short int%d\n\t_C_int int%d\n\t_C_long int%d\n\t_C_long_long int%d\n)\n\n",
		(int)sizeof(short) * 8, (int)sizeof(int) * 8, (int)sizeof(long) * 8, (int)sizeof(long long) * 8);

	begin("Timespec", sizeof(struct timespec));
	FS(struct timespec, tv_sec, "Sec");
	FS(struct timespec, tv_nsec, "Nsec");
	end(1);

	begin("Timeval", sizeof(struct timeval));
	FS(struct timeval, tv_sec, "Sec");
	FS(struct timeval, tv_usec, "Usec");
	end(1);

	begin("Rusage", sizeof(struct rusage));
	FT(struct rusage, ru_utime, "Utime", "Timeval");
	FT(struct rusage, ru_stime, "Stime", "Timeval");
	FS(struct rusage, ru_maxrss, "Maxrss");
	FS(struct rusage, ru_ixrss, "Ixrss");
	FS(struct rusage, ru_idrss, "Idrss");
	FS(struct rusage, ru_isrss, "Isrss");
	FS(struct rusage, ru_minflt, "Minflt");
	FS(struct rusage, ru_majflt, "Majflt");
	FS(struct rusage, ru_nswap, "Nswap");
	FS(struct rusage, ru_inblock, "Inblock");
	FS(struct rusage, ru_oublock, "Oublock");
	FS(struct rusage, ru_msgsnd, "Msgsnd");
	FS(struct rusage, ru_msgrcv, "Msgrcv");
	FS(struct rusage, ru_nsignals, "Nsignals");
	FS(struct rusage, ru_nvcsw, "Nvcsw");
	FS(struct rusage, ru_nivcsw, "Nivcsw");
	end(1);

	begin("Rlimit", sizeof(struct rlimit));
	FS(struct rlimit, rlim_cur, "Cur");
	FS(struct rlimit, rlim_max, "Max");
	end(1);

	INTTYPE("_Pid_t", pid_t);
	INTTYPE("_Gid_t", gid_t);

	/* Hurd's struct stat starts with st_fstype/st_fsid (st_dev is a macro for
	 * st_fsid) and has st_gen/st_author/st_flags/spare fields we don't expose:
	 * they become Pad_cgo_N. */
	begin("Stat_t", sizeof(struct stat));
	FS(struct stat, st_dev, "Dev");
	FS(struct stat, st_ino, "Ino");
	FS(struct stat, st_mode, "Mode");
	FS(struct stat, st_nlink, "Nlink");
	FS(struct stat, st_uid, "Uid");
	FS(struct stat, st_gid, "Gid");
	FS(struct stat, st_rdev, "Rdev");
	FS(struct stat, st_size, "Size");
	FT(struct stat, st_atim, "Atim", "Timespec");
	FT(struct stat, st_mtim, "Mtim", "Timespec");
	FT(struct stat, st_ctim, "Ctim", "Timespec");
	FS(struct stat, st_blksize, "Blksize");
	FS(struct stat, st_blocks, "Blocks");
	end(1);

	begin("Flock_t", sizeof(struct flock));
	FS(struct flock, l_type, "Type");
	FS(struct flock, l_whence, "Whence");
	FS(struct flock, l_start, "Start");
	FS(struct flock, l_len, "Len");
	FS(struct flock, l_pid, "Pid");
	end(1);

	/* d_name is variable length; expose a 256-byte name and skip the size check. */
	begin("Dirent", sizeof(struct dirent));
	FS(struct dirent, d_fileno, "Ino");
	FS(struct dirent, d_reclen, "Reclen");
	FS(struct dirent, d_type, "Type");
	FS(struct dirent, d_namlen, "Namlen");
	addf(offsetof(struct dirent, d_name), 256, "Name", "int8", 0, 256);
	end(0);

	begin("Termios", sizeof(struct termios));
	FS(struct termios, c_iflag, "Iflag");
	FS(struct termios, c_oflag, "Oflag");
	FS(struct termios, c_cflag, "Cflag");
	FS(struct termios, c_lflag, "Lflag");
	FA(struct termios, c_cc, "Cc", "uint8", 1);
	FS(struct termios, c_ispeed, "Ispeed");
	FS(struct termios, c_ospeed, "Ospeed");
	end(1);

	begin("FdSet", sizeof(fd_set));
	FA(fd_set, fds_bits, "Bits", "int64", 8);
	end(1);

#ifndef NO_SOCK
	INTTYPE("_Socklen", socklen_t);

	begin("RawSockaddrInet4", sizeof(struct sockaddr_in));
	FS(struct sockaddr_in, sin_len, "Len");
	FS(struct sockaddr_in, sin_family, "Family");
	FS(struct sockaddr_in, sin_port, "Port");
	FA(struct sockaddr_in, sin_addr, "Addr", "byte", 1);
	FA(struct sockaddr_in, sin_zero, "Zero", "int8", 1);
	end(1);

	begin("RawSockaddrInet6", sizeof(struct sockaddr_in6));
	FS(struct sockaddr_in6, sin6_len, "Len");
	FS(struct sockaddr_in6, sin6_family, "Family");
	FS(struct sockaddr_in6, sin6_port, "Port");
	FS(struct sockaddr_in6, sin6_flowinfo, "Flowinfo");
	FA(struct sockaddr_in6, sin6_addr, "Addr", "byte", 1);
	FS(struct sockaddr_in6, sin6_scope_id, "Scope_id");
	end(1);

	begin("RawSockaddrUnix", sizeof(struct sockaddr_un));
	FS(struct sockaddr_un, sun_len, "Len");
	FS(struct sockaddr_un, sun_family, "Family");
	FA(struct sockaddr_un, sun_path, "Path", "int8", 1);
	end(1);

	begin("RawSockaddr", sizeof(struct sockaddr));
	FS(struct sockaddr, sa_len, "Len");
	FS(struct sockaddr, sa_family, "Family");
	FA(struct sockaddr, sa_data, "Data", "int8", 1);
	end(1);

	{
		size_t big = sizeof(struct sockaddr_in);
		if (sizeof(struct sockaddr_in6) > big)
			big = sizeof(struct sockaddr_in6);
		if (sizeof(struct sockaddr_un) > big)
			big = sizeof(struct sockaddr_un);
		if (sizeof(struct sockaddr) > big)
			big = sizeof(struct sockaddr);
		printf("type RawSockaddrAny struct {\n\tAddr RawSockaddr\n\tPad [%d]int8\n}\n\n",
			(int)(big - sizeof(struct sockaddr)));
		sockaddr_any_size = big;
		asserted[nasserted] = "RawSockaddrAny";
		assertedsz[nasserted] = big;
		nasserted++;
	}

	begin("Linger", sizeof(struct linger));
	FS(struct linger, l_onoff, "Onoff");
	FS(struct linger, l_linger, "Linger");
	end(1);

	begin("Iovec", sizeof(struct iovec));
	FT(struct iovec, iov_base, "Base", "*byte");
	FS(struct iovec, iov_len, "Len");
	end(1);

	begin("IPMreq", sizeof(struct ip_mreq));
	FA(struct ip_mreq, imr_multiaddr, "Multiaddr", "byte", 1);
	FA(struct ip_mreq, imr_interface, "Interface", "byte", 1);
	end(1);

	begin("IPv6Mreq", sizeof(struct ipv6_mreq));
	FA(struct ipv6_mreq, ipv6mr_multiaddr, "Multiaddr", "byte", 1);
	FS(struct ipv6_mreq, ipv6mr_interface, "Interface");
	end(1);

	begin("Msghdr", sizeof(struct msghdr));
	FT(struct msghdr, msg_name, "Name", "*byte");
	FS(struct msghdr, msg_namelen, "Namelen");
	FT(struct msghdr, msg_iov, "Iov", "*Iovec");
	FS(struct msghdr, msg_iovlen, "Iovlen");
	FT(struct msghdr, msg_control, "Control", "*byte");
	FS(struct msghdr, msg_controllen, "Controllen");
	FS(struct msghdr, msg_flags, "Flags");
	end(1);

	begin("Cmsghdr", sizeof(struct cmsghdr));
	FS(struct cmsghdr, cmsg_len, "Len");
	FS(struct cmsghdr, cmsg_level, "Level");
	FS(struct cmsghdr, cmsg_type, "Type");
	end(1);

	begin("Inet6Pktinfo", sizeof(struct in6_pktinfo));
	FA(struct in6_pktinfo, ipi6_addr, "Addr", "byte", 1);
	FS(struct in6_pktinfo, ipi6_ifindex, "Ifindex");
	end(1);

	begin("ICMPv6Filter", sizeof(struct icmp6_filter));
	FA(struct icmp6_filter, icmp6_filt, "Filt", "uint32", 4);
	end(1);

	printf("const (\n");
	SZ("SizeofSockaddrInet4", struct sockaddr_in);
	SZ("SizeofSockaddrInet6", struct sockaddr_in6);
	SZ("SizeofSockaddrUnix", struct sockaddr_un);
	SZ("SizeofLinger", struct linger);
	SZ("SizeofIPMreq", struct ip_mreq);
	SZ("SizeofIPv6Mreq", struct ipv6_mreq);
	SZ("SizeofMsghdr", struct msghdr);
	SZ("SizeofCmsghdr", struct cmsghdr);
	SZ("SizeofInet6Pktinfo", struct in6_pktinfo);
	SZ("SizeofICMPv6Filter", struct icmp6_filter);
	printf("\tSizeofSockaddrAny = 0x%zx\n", sockaddr_any_size);
	printf(")\n\n");
#endif

	printf("const _AT_FDCWD = %d\n\n", AT_FDCWD);

	printf("// Compile-time layout assertions: an index into a 1-element array is only\n");
	printf("// valid when the Go struct size equals the C size measured on Hurd.\n");
	{
		int i;
		for (i = 0; i < nasserted; i++)
			printf("var _ = [1]struct{}{}[unsafe.Sizeof(%s{})-0x%zx]\n", asserted[i], assertedsz[i]);
	}
	return 0;
}
