#!/usr/bin/env python3
"""Build a vmlab scenario (for `vmlab.py run --guest windows-install.json`)
out of vmlab/guests/win-jobs/NN-*.ps1: wraps each job file as a
payload/waitupload/catupload/shot step around the guest's PowerShell agent
(vmlab/guests/windows-agent.ps1), same job.ps1/job.out convention as
ctl.py's `sh`. Kept separate from the checked-in job scripts so each one
stays a readable, individually-editable .ps1 file instead of a hand-rolled
base64 blob; stdlib only, run before vmlab.py itself.

  windows-install-gen.py OUT.txt              full run: boot + all jobs
  windows-install-gen.py OUT.txt --resume     resume: `--loadvm postinstall`
                                               brings QEMU up already past
                                               00-hello.ps1, so skip the BIOS
                                               boot preamble and that job
"""
import base64
import glob
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_TIMEOUT = 300

HEAD = """\
# GENERATED by vmlab/guests/windows-install-gen.py -- do not hand-edit.
# Boot the Windows Server 2022 eval ISO with a real disk + floppy-borne
# autounattend.xml attached (vmlab/guests/windows-install.json); Setup
# applies the answer file with no UI from here (see autounattend.xml) --
# partition, copy, expand, specialize, one internal reboot, oobeSystem
# FirstLogonCommands -> bootstrap.ps1 -> our agent. Minutes, not seconds.
wait 8
shot bios
key ret
wait 5
shot loading
"""


def jobs():
    return sorted(glob.glob(os.path.join(HERE, "win-jobs", "*.ps1")))


def job_step(path, index):
    name = os.path.basename(path)
    body = open(path, encoding="utf-8").read()
    timeout = DEFAULT_TIMEOUT
    m = re.match(r"^#\s*TIMEOUT=(\d+)\s*\n", body)
    if m:
        timeout = int(m.group(1))
        body = body[m.end():]
    nonce = "# %d\n" % int(time.time() * 1000 + index)
    b64 = base64.b64encode((nonce + body).encode()).decode()
    step = os.path.splitext(name)[0]
    lines = [
        "# ---- job %s ----\n" % name,
        "payload job.ps1 %s\n" % b64,
        "waitupload job.out %d\n" % timeout,
        "catupload job.out\n",
        "shot after-%s\n" % re.sub(r"[^\w.-]", "_", step),
    ]
    if index == 0:
        # First real checkpoint after the install itself: snapshot the
        # persistent disk now, before anything WSL2-related, so a failure
        # further down doesn't cost re-running the ~20-40min unattended
        # install on the next iteration (see vmlab-windows-install.yml).
        lines.append("save postinstall\n")
    return "".join(lines)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "scenarios", "windows-install.txt")
    resume = "--resume" in sys.argv[2:]
    job_files = jobs()
    if not job_files:
        raise SystemExit("no vmlab/guests/win-jobs/*.ps1 found")
    parts = []
    start = 0
    if resume:
        parts.append("# resume: --loadvm postinstall already lands past 00-hello.ps1\n")
        start = 1
    else:
        parts.append(HEAD)
    for i, path in enumerate(job_files):
        if i < start:
            continue
        parts.append(job_step(path, i))
    open(out, "w").write("".join(parts))
    print("wrote %s (%d/%d jobs%s)" % (out, len(job_files) - start, len(job_files), ", resume" if resume else ""))


if __name__ == "__main__":
    main()
