#!/usr/bin/env python3
"""Generate xsys-redox/unix/zconst_redox_amd64.go: `NAME = syscall.NAME` for every
constant the redox syscall package defines (errnos, signals, O_*, F_*, ...), except the
names defined by hand in unix/const_redox.go.
usage: gen_zconst.py GOROOT UNIXDIR"""
import re, sys, os
goroot, unixdir = sys.argv[1], sys.argv[2]
src = open(os.path.join(goroot, 'src/syscall/zerrors_redox_amd64.go')).read()
manual = set()
for mf in ('const_redox.go', 'ztermios_redox_amd64.go'):
    manual |= set(re.findall(r'^\s+([A-Z_][A-Za-z0-9_]*)\s+=', open(os.path.join(unixdir, mf)).read(), re.M))
names = []
for m in re.finditer(r'^\s+([A-Z][A-Za-z0-9_]*)\s+=\s', src, re.M):
    n = m.group(1)
    if n not in manual and n not in names:
        names.append(n)
out = ['// Code generated by gen_zconst.py; DO NOT EDIT.', '', '//go:build redox && amd64', '', 'package unix', '',
       'import "syscall"', '', 'const (']
out += [f'\t{n} = syscall.{n}' for n in names]
out.append(')')
open(os.path.join(unixdir, 'zconst_redox_amd64.go'), 'w').write('\n'.join(out) + '\n')
print(f'gen_zconst: {len(names)} constants aliased, {len(manual)} manual', file=sys.stderr)
