#!/usr/bin/env python3
"""Generate zconsts_hurd.go for the golang.org/x/sys/unix hurd shim: re-export every
constant of GOROOT/src/syscall/zerrors_hurd_amd64.go (measured on real Hurd) that the
hand-written shim does not define itself. Usage: gen_unix_consts.py ZERRORS.go SHIMDIR OUT.go"""
import re, sys, glob

zerr, shimdir, out = sys.argv[1:4]
have = set()
for p in glob.glob(shimdir + '/*.go'):
    src = open(p).read()
    for m in re.finditer(r'^(?:const|func|type|var)\s+([A-Za-z_][A-Za-z0-9_]*)', src, re.M):
        have.add(m.group(1))
    for blk in re.finditer(r'^(?:const|var|type)\s*\((.*?)^\)', src, re.M | re.S):
        for m in re.finditer(r'^\t([A-Za-z_][A-Za-z0-9_]*)\b', blk.group(1), re.M):
            have.add(m.group(1))
names = []
in_const = False
for line in open(zerr):
    if line.startswith('const ('):
        in_const = True
        continue
    if in_const and line.startswith(')'):
        in_const = False
        continue
    if in_const:
        m = re.match(r'\t([A-Z][A-Za-z0-9_]*)\s*=', line)
        if m and m.group(1) not in have:
            names.append(m.group(1))
with open(out, 'w') as f:
    f.write('// Code generated by gen_unix_consts.py from syscall/zerrors_hurd_amd64.go; DO NOT EDIT.\n\n')
    f.write('//go:build hurd\n\npackage unix\n\nimport "syscall"\n\nconst (\n')
    for n in sorted(set(names)):
        f.write('\t%s = syscall.%s\n' % (n, n))
    f.write(')\n')
print('%d constants' % len(set(names)))
